### ISSUE TITLE
System Ready

### ISSUE THREAD

**Issue by fhogan** [mcubelab/rgrasp#16]
@OleguerCanal @mariabauza 

We are ready to start the initial data collection. 

I added the rostopic for contact detection time. Also the passive vision rgbd snapshot are saved separately for now in path "/rgraspdata/passive_vision_data" with time stamps. Ideally they will be formatted together with all the other data but for now let's go with that. Let's hope the current setup is sufficient to dedicate the day of tomorrow for data collection.

@OleguerCanal If you spend lab in the lab tonight, can you start the system with the standard staples object?

@mariabauza If you arrive before me tomorrow am, can you start the system with the standard staples object?

Hopefully we will have a sufficient amount of data to start testing out different network architectures by this weekend. Let me know if I am forgetting something.

**Comment by mariabauza** [comment]
Hi, 
The system has been running for more than 20min so far without problems :-)
