### ISSUE TITLE
The robot stopped with the object in hand, then continued

### ISSUE THREAD

**Issue by mariabauza** [mcubelab/rgrasp#28]
@fhogan  @OleguerCanal 

What happened:
1. Robot stopped moving with the object in hand
2. I removed the object and put it back into the tote
3. The robot started moving again and continued the execution as if nothing had happened.

I took a screenshot of the terminal, but not sure if it will be enough to debug.
![screenshot from 2017-10-27 08-47-14](https://user-images.githubusercontent.com/24418956/32104754-c6f6e1dc-baf3-11e7-9677-6996731f5c22.png)

**Comment by mariabauza** [comment]
The only idea that comes to my mind to explain this is:
1. The robot grasped the object, but the execution was marked as False (success = False)
2. As a result, there where no more grasp proposals in any of the bins so the robot had nothing to do and remained stopped.
3. Once I put the object back, new grasp proposals appeared and the execution restarted.

By now, what we can do is to fully open the gripper in case the execution is false.

**Comment by fhogan** [comment]
I think Maria's fix solves the problem for the time being. I will close this issue.
