### ISSUE TITLE
Proper data collection

### ISSUE THREAD

**Issue by mariabauza** [mcubelab/rgrasp#30]
@fhogan @OleguerCanal

I have been looking at the data and here there are some issues:

1. For RGB: To go from our np-array images to a png plot it is not a direct transformation, I think the order of the channels will need to be changed  [1,2,3] (1st image) --> [3,2,1] (2nd image).

![figure_1](https://user-images.githubusercontent.com/24418956/32171780-b365f848-bd4f-11e7-979b-a146d52c6de5.png)
![figure_2](https://user-images.githubusercontent.com/24418956/32171782-b37e445c-bd4f-11e7-98d0-df722891bc1f.png)

2. For Depth: To go from our np-array images to a png plot it is not looking good and changing the channels does not solve the problem ([1,2,3] 3rd image, [3,2,1] 4thnd image):

![figure_3](https://user-images.githubusercontent.com/24418956/32171783-b3888a98-bd4f-11e7-9a8f-a4bc2209f08e.png)
![figure_4](https://user-images.githubusercontent.com/24418956/32171784-b394146c-bd4f-11e7-9437-b731aa830c61.png)

3. Impact time has been recorded as False.

4. The object ID does not appear in the experiment_summary.

**Comment by fhogan** [comment]
@OleguerCanal 

I think you looked into this. Can you update this issue please.

**Comment by OleguerCanal** [comment]
Everything should be fine, once we have the new gui for visualization we can easily check it
