### ISSUE TITLE
Passive vision is not working, return 0 proposals

### ISSUE THREAD

**Issue by mariabauza** [mcubelab/rgrasp#32]
@fhogan @OleguerCanal 

I have been trying to make passive vision work but it always returns 0 proposals. Any idea? Have you changed anything that can affect it?

Maria

**Comment by fhogan** [comment]
Maria,

No I havent changed anything. I would try:

1) making sure lasers work
2) make sure no object in tote and restart passive vision
3) reset usb ports

Ill be in the lab in 5min.

**Comment by mariabauza** [comment]
The issue seems to have been caused when restarting the computer, the cameras don't get properly initialized and the lasers don't work. If this happens again, see https://github.com/mcubelab/rgrasp/wiki/Vision-System.

@written by fhogan
