### ISSUE TITLE
Publish object ID and weigth

### ISSUE THREAD

**Issue by fhogan** [mcubelab/rgrasp#4]
@mariabauza 

We need to publish and record the object ID and known weight. You mentioned yesterday that you will need a list of object list. Can you look into this please?

**Comment by mariabauza** [comment]
I am just publishing the object ID so far. When we deal with clutter, I will add the weight identification.

**Comment by fhogan** [comment]
@mariabauza 

I think we will start experiments in clutter shortly and will need this functionality soon.

**Comment by fhogan** [comment]
This has been implemented.
