### ISSUE TITLE
Weekly goals

### ISSUE THREAD

**Issue by fhogan** [mcubelab/rgrasp#45]
@mariabauza @OleguerCanal @albertor 

I thought github issue tracker might be a nice place to write our weekly objectives. Here are the objectives we set during the meeting yesterday:

1) Add noise to grasp proposal issue 
2) Add image processing functions (resizing, background subtraction) to dataset  
3) Filter grasps and select 2 (before and after) liftoff time
4) Train grasp stability with different sensor modalities
5) Data transfer optimization between robot computer and training computer

**Comment by mariabauza** [comment]
Point 1. has been tested and the number of failures now is between 60% and 30% which is good.
