### ISSUE TITLE
Bugs in grasp_data_recorder.py

### ISSUE THREAD

**Issue by fhogan** [mcubelab/rgrasp#49]
@OleguerCanal 

There are bugs in master in the new implementation of recording the wsg_driver format. In the future, either

1) Implement your new changes on a remote branch, test, and then merge with master

or 

2) At the very least, test that there are no bugs if you add your changes directly to master. 

See snapshot below:

![screenshot from 2017-12-09 11-50-25](https://user-images.githubusercontent.com/26258173/33797513-37d2b340-dcd7-11e7-9056-d72e9f7781c3.png)

**Comment by OleguerCanal** [comment]
I'm sorry, I couldn't test it with the robot not running.

Maybe it is solved by changing the line 144 from:
ws50messsage = data.data
to:
ws50message = data

If that doesn't work let me know and I'll come and try to fix it.

Again, I'm very sorry.

**Comment by fhogan** [comment]
It's no problem at all. I had to stop the experiments anyway because I'm having issues with the gripper. Also, the bugs are not breaking, we can still run the experiments, it just doesn't save the gripper state. It was more of a FYI than an urgency.

**Comment by fhogan** [comment]
@OleguerCanal 

Did you get a chance to look into this?
