### ISSUE TITLE
Broken spatula

### ISSUE THREAD

**Issue by fhogan** [mcubelab/rgrasp#50]
@mariabauza @OleguerCanal @albertor @mcubelab/design @elliott

The actuation for the spatula is broken. It is my fault. I was testing the guarded move this morning with the new finger. I was trying to see if bringing the tolerance down on the weight sensors would allow smoother guarded moves with the new rigid spatula. I believe it is the transmission that took the hit. 

@albertor 

With the new finger, guarded move is possible when performing grasps as the finger has an open angle relative to the ground. However, when placing, the angle is perpendicular to the ground and the impact is large.

The video of the failure is attached here:

https://youtu.be/anvdHHzgqpk

**Comment by albertor** [comment]
Oh, boy.

I can't see the video. It says "Video unavailable"

**Comment by EZas456** [comment]
It's fixed. I might have to make another modification later to help it not
break again but it works.
