### ISSUE TITLE
Saved RGB data weird color

### ISSUE THREAD

**Issue by fhogan** [mcubelab/rgrasp#7]
@OleguerCanal 

Any idea why the recorded rgb has the color blue for the bins?
![screenshot from 2017-10-18 10-06-05](https://user-images.githubusercontent.com/26258173/31723292-6d98d842-b3ec-11e7-9c78-86d4ac5060d5.png)

**Comment by albertor** [comment]
Cool :)
I am going to guess an RGB vs BGR confusion in transcoding the images?

**Comment by fhogan** [comment]
Precisely! Good catch thanks.
